name: Multiple Jobs with Node.js Matrix

on:
  push:
    branches:
      - main
env:
  Today: wednesday
jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Print Message from Job 1
      run: echo " 'job 1 tested',${{matrix.node-version}},'today is ',$Today"

  job-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Print Message from Job 2
      run: echo " 'job 2 tested',${{matrix.node-version}}"
